<?php 
$eng_to_viet = array
    (
    "hello" => "Xin Chao",
	"goodbye" => "Tam Biet",
	"apple" => "táo",
	"ant" => "kiến",
	"pig" => "heo",
	"tiger" => "hổ",
	"cat" => "nèo",
	"banana" => "chuối",
	"flower" => "hoa",
	"dog" => "chó",
	"food" => "đồ ăn",
	"friend" => "bạn",
	"husband" => "chồng",
	"book" => "sách",
	"computer" => "máy tính",
	"school" => "trường",
	"car" => "xe",
	"road" => "đường",
	"father" => "ba",
	"mother" => "mẹ",
	"daughter" => "con gái",
	"uncle" => "chú",
	"drink" => "uống",
	"rice" => "cơm",
	"sky" => "trời",
	"man" => "đàn ông",
	"mirror" => "gương",
	"pen" => "bút mực",
	"clothes" => "quần áo",
	"hat" => "mũ",
	"bag" => "túi",
	"house" => "nhà",
	"tree" => "cây",
	"run" => "chạy",
	"eat" => "ăn"
    );
?>